### ISSUE TITLE
[enhancement] I wanna use env variables to set the logfile path

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-log#4]
issued by @jmleefree 

아래 cb-store 이슈와 같은 이슈
- https://github.com/cloud-barista/cb-store/issues/13

**Comment by powerkimhub** [comment]
completed. 
ref) https://github.com/cloud-barista/cb-log/commit/dd4f9916236bb0e5fa6772edf849867ab193b919

<TO-BE>

```
logfileinfo:
  #filename: ./log/cblogs.log
  filename: $CBLOG_ROOT/log/cblogs.log
  maxsize: 10 # megabytes
  maxbackups: 50
  maxage: 31 # days

```
